# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: /llc/:year/:month/:title
permaklink: /404.html

# Setup
title: 'CoreyWeiner'
tagline:  "The world is full of 0's and 1's"
description: 'My personal website'
url: http://corey-weiner.com
logo: "/assets/images/icon.png"
paginate_path: /llc/page:num
commentsystem: disqus
disqus: example

# Gems
gems:
  - jekyll-sitemap

author:
  name: 'Corey Weiner'
  image: https://s.gravatar.com/avatar/a8002a37119322b475cbf5a10beae6e0?s=200
  url: 	http://www.twitter.com/cjweiner

blog:
  title: 'Live, Laugh, Code!'


paginate: 5

icon: /assets/images/icon.png
cover: /assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/cjweiner
    desc:	Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/cjweiner
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: google-plus
    url: https://google.com/+CoreyWeiner09
    desc: Add me to your circle
    share_url:
    share_title:
    share_link:

  - icon: linkedin-square
    url: https://www.linkedin.com/pub/corey-weiner/26/759/348
    desc: Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:

menu:
  - title: Home
    url: /
    visibleOnHomepage: false

  - title: About
    url: /about
    visibleOnHomepage: true

  - title: Blog
    url: /llc
    visibleOnHomepage: true

copyright:
   author: Weiner
   type_title: Some rights reserved
   type_url: http://creativecommons.org/licenses/by-nc/2.5

google_analytics: UA-53933218-1